# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=200)),
                ('banner_description', models.TextField(max_length=1023)),
                ('banner_image', models.ImageField(default='static/img/banner.jpg', upload_to='static/img/')),
                ('banner_button', models.CharField(max_length=200)),
                ('banner_button_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_image', models.ImageField(default='static/img/card.jpg', upload_to='static/img/')),
                ('card_name', models.CharField(max_length=200)),
                ('card_description', models.TextField(max_length=1023)),
                ('card_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_title', models.CharField(max_length=200)),
                ('footer_description', models.TextField(max_length=1023)),
                ('footer_link_name', models.CharField(max_length=200)),
                ('footer_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_title', models.CharField(max_length=200)),
                ('footer_url_name_1', models.CharField(max_length=200)),
                ('footer_url_1', models.URLField()),
                ('footer_url_name_2', models.CharField(max_length=200)),
                ('footer_url_2', models.URLField()),
                ('footer_url_name_3', models.CharField(max_length=200)),
                ('footer_url_3', models.URLField()),
                ('footer_url_name_4', models.CharField(max_length=200)),
                ('footer_url_4', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_title', models.CharField(max_length=200)),
                ('footer_url_name_1', models.CharField(max_length=200)),
                ('footer_url_1', models.URLField()),
                ('footer_url_name_2', models.CharField(max_length=200)),
                ('footer_url_2', models.URLField()),
                ('footer_url_name_3', models.CharField(max_length=200)),
                ('footer_url_3', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_title', models.CharField(max_length=200)),
                ('footer_description', models.TextField(max_length=1023)),
                ('footer_link_name', models.CharField(max_length=200)),
                ('footer_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=200)),
                ('menu_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200)),
                ('site_logo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(default='static/img/slider.jpg', upload_to='static/img/')),
                ('slider_title', models.CharField(max_length=200)),
                ('slider_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_title', models.CharField(max_length=200)),
                ('subscribe_description', models.TextField(max_length=1023)),
                ('subscribe_button', models.CharField(max_length=200)),
                ('subscribe_button_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=200)),
                ('video_description', models.TextField(max_length=1023)),
                ('video_url', models.URLField()),
            ],
        ),
    ]
