# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_file', models.FileField(default='static/css/default.theme', upload_to='static/css/')),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='card_image',
            field=models.FileField(default='static/icon/card.svg', upload_to='static/icon/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(default='static/img/logo.jpg', upload_to='static/img/'),
        ),
    ]
