# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20180630_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='theme_name',
            field=models.CharField(default='Gold Munsell', max_length=200),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme_file',
            field=models.FileField(default='static/css/default.th', upload_to='static/css/'),
        ),
    ]
