# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20180630_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coloring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coloring_name', models.CharField(default='Gold Munsell', max_length=200)),
                ('coloring_file', models.FileField(default='static/css/default.th', upload_to='static/css/')),
            ],
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
