# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20180630_0851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coloring',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_theme',
            field=models.FileField(default='static/css/default.cl', upload_to='static/css/'),
        ),
    ]
