# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20180630_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer1',
            name='footer_description',
        ),
        migrations.AddField(
            model_name='footer1',
            name='footer_district',
            field=models.TextField(default='022', max_length=1023),
        ),
        migrations.AddField(
            model_name='footer1',
            name='footer_phone',
            field=models.CharField(default='022', max_length=200),
        ),
        migrations.AddField(
            model_name='footer1',
            name='footer_street',
            field=models.TextField(default='022', max_length=1023),
        ),
        migrations.AddField(
            model_name='footer4',
            name='footer_end',
            field=models.CharField(default='022', max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='video_poster',
            field=models.ImageField(default='static/img/poster.jpg', upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_theme',
            field=models.FileField(default='static/css/default.css', upload_to='static/css/'),
        ),
    ]
